name: Check PR Title

on:
  pull_request:
    types: [opened, edited]

jobs:
  lint-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: commitlint.config.js

      - name: Install dependencies
        run: npm install --global @commitlint/config-conventional commitlint

      - name: Check PR title with commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint
