name: Check PR Title

on:
  pull_request:
    types: [opened, edited]

jobs:
  lint-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: commitlint.config.js

      - name: Install dependencies
        run: npm install --global @commitlint/config-conventional commitlint

      - name: Check PR title with commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint
