name: Release + Publish

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@54045abd5dcd3b0fee9ca02fa24c57545834c9cc # v6.2.0
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global push.followTags true

      - name: Generate changelog and release notes
        run: |
          npx changelogen --hideAuthorEmail --release --no-push

      - name: Get metadata
        run: |
          VERSION=$(jq -r '.version' package.json)
          NAME=$(jq -r '.name' package.json)

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "NAME=$NAME" >> $GITHUB_ENV

      - name: Sync version to workspace packages
        run: |
          VERSION=$(jq -r '.version' package.json)
          npm version $VERSION --workspaces --no-git-tag-version
          git add packages/*/package.json
          git commit --amend --no-edit
          git push --follow-tags

      - name: Create GitHub release
        run: npx changelogen github release --token ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build

      - name: Copy README and LICENSE to CLI package
        run: |
          cp README.md packages/cli/
          cp LICENSE packages/cli/

      - name: Publish to NPM Registry
        run: npm publish --provenance --access public -w prune-overrides
